big_cities:
  New York,New York,
  Los Angeles,California,
  Chicago,Illinois,
  Houston,Texas,
  Phoenix,Arizona,
  Philadelphia,Pennsylvania,
  San Antonio,Texas,
  Dallas,Texas,
  San Diego,California,
  San Jose,California,
  Detroit,Michigan,
  San Francisco,California,
  Jacksonville,Florida,
  Indianapolis,Indiana,
  Austin,Texas,
  Columbus,Ohio,
  Fort Worth,Texas,
  Charlotte,North Carolina,
  Memphis,Tennessee,
  Baltimore,Maryland,
  El Paso,Texas,
  Boston,Massachusetts,
  Milwaukee,Wisconsin,
  Denver,Colorado,
  Seattle,Washington,
  Nashville,Tennessee,
  Washington,District of Columbia,
  Las Vegas,Nevada,
  Portland,Oregon,
  Louisville,Kentucky,
  Oklahoma City,Oklahoma,
  Tucson,Arizona,
  Atlanta,Georgia

wwhow_locations:
  Birmingham, Alabama,
  Montgomery, Alabama,
  Mobile, Alabama,
  Huntsville, Alabama,
  Anchorage, Alaska,
  Phoenix, Arizona,
  Tucson, Arizona,
  Mesa, Arizona,
  Glendale, Arizona,
  Chandler, Arizona,
  Scottsdale, Arizona,
  Gilbert, Arizona,
  Tempe, Arizona,
  Peoria, Arizona,
  Little Rock, Arkansas,
  Los Angeles, California,
  San Diego, California,
  San Jose, California,
  San Francisco, California,
  Fresno, California,
  Sacramento, California,
  Long Beach, California,
  Oakland, California,
  Santa Ana, California,
  Anaheim, California,
  Bakersfield, California,
  Riverside, California,
  Stockton, California,
  Chula Vista, California,
  Irvine, California,
  Modesto, California,
  Fremont, California,
  San Bernardino, California,
  Glendale, California,
  Huntington Beach, California,
  Moreno Valley, California,
  Oxnard, California,
  Fontana, California,
  Ontario, California,
  Rancho Cucamonga, California,
  Oceanside, California,
  Santa Clarita, California,
  Garden Grove, California,
  Santa Rosa, California,
  Pomona, California,
  Corona, California,
  Lancaster, California,
  Salinas, California,
  Palmdale, California,
  Pasadena, California,
  Hayward, California,
  Torrance, California,
  Escondido, California,
  Orange, California,
  Elk Grove, California,
  Sunnyvale, California,
  Fullerton, California,
  Thousand Oaks, California,
  El Monte, California,
  Concord, California,
  Visalia, California,
  Simi Valley, California,
  Vallejo, California,
  Inglewood, California,
  Roseville, California,
  Victorville, California,
  Santa Clara, California,
  Costa Mesa, California,
  Downey, California,
  West Covina, California,
  San Buenaventura (Ventura), California,
  Fairfield, California,
  Norwalk, California,
  Burbank, California,
  Richmond, California,
  Daly City, California,
  Berkeley, California,
  Antioch, California,
  Denver, Colorado,
  Colorado Springs, Colorado,
  Aurora, Colorado,
  Lakewood, Colorado,
  Fort Collins, Colorado,
  Thornton, Colorado,
  Arvada, Colorado,
  Westminster, Colorado,
  Pueblo, Colorado,
  Bridgeport, Connecticut,
  Hartford, Connecticut,
  New Haven, Connecticut,
  Stamford, Connecticut,
  Waterbury, Connecticut,
  Washington, District of Columbia,
  Jacksonville, Florida,
  Miami, Florida,
  Tampa, Florida,
  St. Petersburg, Florida,
  Orlando, Florida,
  Hialeah, Florida,
  Fort Lauderdale, Florida,
  Tallahassee, Florida,
  Cape Coral, Florida,
  Port St. Lucie, Florida,
  Pembroke Pines, Florida,
  Hollywood, Florida,
  Coral Springs, Florida,
  Gainesville, Florida,
  Miami Gardens, Florida,
  Miramar, Florida,
  Clearwater, Florida,
  Pompano Beach, Florida,
  Palm Bay, Florida,
  Atlanta, Georgia,
  Augusta, Georgia,
  Columbus, Georgia,
  Savannah, Georgia,
  Athens, Georgia,
  Honolulu b[›], Hawaii,
  Boise, Idaho,
  Chicago, Illinois,
  Aurora, Illinois,
  Rockford, Illinois,
  Joliet, Illinois,
  Naperville, Illinois,
  Springfield, Illinois,
  Peoria, Illinois,
  Elgin, Illinois,
  Indianapolis, Indiana,
  Fort Wayne, Indiana,
  Evansville, Indiana,
  South Bend, Indiana,
  Des Moines, Iowa,
  Cedar Rapids, Iowa,
  Davenport, Iowa,
  Wichita, Kansas,
  Overland Park, Kansas,
  Kansas City, Kansas,
  Topeka, Kansas,
  Olathe, Kansas,
  Louisville, Kentucky,
  Lexington, Kentucky,
  New Orleans, Louisiana,
  Baton Rouge, Louisiana,
  Shreveport, Louisiana,
  Lafayette, Louisiana,
  Baltimore, Maryland,
  Boston, Massachusetts,
  Worcester, Massachusetts,
  Springfield, Massachusetts,
  Cambridge, Massachusetts,
  Lowell, Massachusetts,
  Detroit, Michigan,
  Grand Rapids, Michigan,
  Warren, Michigan,
  Sterling Heights, Michigan,
  Ann Arbor, Michigan,
  Lansing, Michigan,
  Flint, Michigan,
  Minneapolis, Minnesota,
  St. Paul, Minnesota,
  Rochester, Minnesota,
  Jackson, Mississippi,
  Kansas City, Missouri,
  St. Louis, Missouri,
  Springfield, Missouri,
  Independence, Missouri,
  Columbia, Missouri,
  Billings, Montana,
  Omaha, Nebraska,
  Lincoln, Nebraska,
  Las Vegas, Nevada,
  Henderson, Nevada,
  North Las Vegas, Nevada,
  Reno, Nevada,
  Manchester, New Hampshire,
  Newark, New Jersey,
  Jersey City, New Jersey,
  Paterson, New Jersey,
  Elizabeth, New Jersey,
  Albuquerque, New Mexico,
  New York City, New York,
  Buffalo, New York,
  Rochester, New York,
  Yonkers, New York,
  Syracuse, New York,
  Charlotte, North Carolina,
  Raleigh, North Carolina,
  Greensboro, North Carolina,
  Durham, North Carolina,
  Winston-Salem, North Carolina,
  Fayetteville, North Carolina,
  Cary, North Carolina,
  High Point, North Carolina,
  Wilmington, North Carolina,
  Columbus, Ohio,
  Cleveland, Ohio,
  Cincinnati, Ohio,
  Toledo, Ohio,
  Akron, Ohio,
  Dayton, Ohio,
  Oklahoma City, Oklahoma,
  Tulsa, Oklahoma,
  Norman, Oklahoma,
  Portland, Oregon,
  Salem, Oregon,
  Eugene, Oregon,
  Gresham, Oregon,
  Philadelphia, Pennsylvania,
  Pittsburgh, Pennsylvania,
  Allentown, Pennsylvania,
  Erie, Pennsylvania,
  Providence, Rhode Island,
  Columbia, South Carolina,
  Charleston, South Carolina,
  Sioux Falls, South Dakota,
  Memphis, Tennessee,
  Nashville, Tennessee,
  Knoxville, Tennessee,
  Chattanooga, Tennessee,
  Clarksville, Tennessee,
  Murfreesboro, Tennessee,
  Houston, Texas,
  San Antonio, Texas,
  Dallas, Texas,
  Austin, Texas,
  Fort Worth, Texas,
  El Paso, Texas,
  Arlington, Texas,
  Corpus Christi, Texas,
  Plano, Texas,
  Laredo, Texas,
  Lubbock, Texas,
  Garland, Texas,
  Irving, Texas,
  Amarillo, Texas,
  Brownsville, Texas,
  Grand Prairie, Texas,
  Pasadena, Texas,
  Mesquite, Texas,
  McAllen, Texas,
  Carrollton, Texas,
  Waco, Texas,
  McKinney, Texas,
  Denton, Texas,
  Killeen, Texas,
  Abilene, Texas,
  Beaumont, Texas,
  Midland, Texas,
  Round Rock, Texas,
  Lewisville, Texas,
  Richardson, Texas,
  Wichita Falls, Texas,
  Salt Lake City, Utah,
  West Valley City, Utah,
  Provo, Utah,
  West Jordan, Utah,
  Virginia Beach, Virginia,
  Norfolk, Virginia,
  Chesapeake, Virginia,
  Arlington, Virginia,
  Richmond, Virginia,
  Newport News, Virginia,
  Hampton, Virginia,
  Alexandria, Virginia,
  Portsmouth, Virginia,
  Seattle, Washington,
  Spokane, Washington,
  Tacoma, Washington,
  Vancouver, Washington,
  Bellevue, Washington,
  Milwaukee, Wisconsin,
  Madison, Wisconsin,
  Green Bay, Wisconsin